### ISSUE TITLE
Route and ID Parameter Support

### ISSUE THREAD

**Issue by edm00se** [tfiwm/grunt-json-server#7]
Feature Request: add parameters for [routes](https://github.com/typicode/json-server#routes) and [id](https://github.com/typicode/json-server/issues/103) options.

**Comment by tbprojects** [comment]
This fork supports routes feature: https://github.com/tbprojects/grunt-json-server

**Comment by edm00se** [comment]
Thanks. That one does have the routes part figured out, though I'm mocking a specific back-end, which requires a different ID as well. For now, I think I'm settled on using grunt-run, as I need both.

**Comment by americoneto1** [comment]
@tbprojects did you publish your fork version on npm registry?

**Comment by tfiwm** [comment]
i merged your changes ;) Thanks!

**Comment by americoneto1** [comment]
Thank you @tfiwm !
